version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.1-jdk-11-slim
    branches:
      only:
       - master
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn sonar:sonar -Dsonar.projectKey=Ajris_aws -Dsonar.organization=ajris-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=fd2220871e5656ecc91490c83d7b3ebd72880d26
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ajris/awsik:$TAG .
          docker push ajris/awsik:$TAG