version: 2
jobs:
  build:
    machine: true
    branches:
      only:
       - master
    steps:
      - checkout
      - run: mvn sonar:sonar -Dsonar.projectKey=Ajris_aws -Dsonar.organization=ajris-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=fd2220871e5656ecc91490c83d7b3ebd72880d26